/** Demo UI labels — presentation only, not Domain vocabulary. */
export {
  DEMO_FLOW_STEPS,
  DEMO_ESSENTIAL_COPY,
  getDemoCopy,
  resolveDemoLocale,
  formatDemoPickup,
  formatDemoEuro,
  demoActionMessage,
  demoVehicleTitle,
  demoVehiclePresentation,
  demoCancellationReasonLabel,
  demoAuditEventLabel,
  demoServiceStatusLabel,
  demoBookingStatusLabel,
  demoCancellationReasonLabelIt,
  demoAuditEventLabelIt,
  demoServiceStatusLabelIt,
  demoBookingStatusLabelIt,
} from "./copy";
